### ISSUE TITLE
エラー集

### ISSUE THREAD

**Issue by kagari** [jphacks/E_2202#7]
プロダクトの入力例となりそうなエラー文を収集する

対象外
* syntax error

**Comment by umahara555** [comment]
```
# npx create-next-app@latest --typescript
...
error @eslint/eslintrc@1.3.3: The engine "node" is incompatible with this module. Expected version "^12.22.0 || ^14.17.0 || >=16.0.0". Got "14.3.0"
error Found incompatible module.
```

**Comment by kagari** [comment]
https://docs.python.org/3/tutorial/errors.html#exceptions

```
>>> 10 * (1/0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: division by zero
```

```
>>> 4 + spam*3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'spam' is not defined
```

```
>>> '2' + 2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can only concatenate str (not "int") to str
```

**Comment by kagari** [comment]
```
>>> l = 100
>>> l.append(200)

Traceback (most recent call last):
 File "/Users/mbp/Documents/my-project/python-snippets/errors.py", line 2, in <module>
  l.append(200)
AttributeError: 'int' object has no attribute 'append'
```

**Comment by Hamumayo55** [comment]
'''
ActionView::Template::Error (Missing partial public_activity/post/_created with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee, :jbuilder]}. Searched in:
  * "/home/benjamin/Desktop/stukbook/app/views"
  * "/home/benjamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/twitter-bootstrap-rails-d3776ddd0b89/app/views"
  * "/home/benjamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/devise-4.2.0/app/views"
):
    55:         <div class="panel panel-default">
    56:         <div class="panel-heading">Recent Activity</div>
    57:         <div class="panel-body">
    58:             <%= render_activities(@activities) %>
    59:         </div>
    60:         </div>
    61:     </div>
'''

**Comment by Hamumayo55** [comment]
Ruby on Rails
```
ActionView::Template::Error (Missing partial public_activity/post/_created with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee, :jbuilder]}. Searched in:
  * "/home/benjamin/Desktop/stukbook/app/views"
  * "/home/benjamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/twitter-bootstrap-rails-d3776ddd0b89/app/views"
  * "/home/benjamin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/devise-4.2.0/app/views"
):
    55:         <div class="panel panel-default">
    56:         <div class="panel-heading">Recent Activity</div>
    57:         <div class="panel-body">
    58:             <%= render_activities(@activities) %>
    59:         </div>
    60:         </div>
    61:     </div>
```

**Comment by Hamumayo55** [comment]
Rails
```
NoMethodError in Articles#index

undefined method `each' for nil:NilClass"
```

**Comment by Hamumayo55** [comment]
Rails 
```
routing error 
No route matches [GET] "post/new"
```

**Comment by umahara555** [comment]
```shell
> docker compose run --rm web bash yarn -v
node:internal/modules/cjs/loader:988
  throw err;
  ^

Error: Cannot find module '/usr/src/app/web/yarn.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
    at Function.Module._load (node:internal/modules/cjs/loader:833:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

```

![スクリーンショット 2022-10-16 19 27 52](https://user-images.githubusercontent.com/33239435/196030382-8118b74a-b439-4916-ae41-3762b3dad10e.png)

**Comment by umahara555** [comment]
> ```shell
> > docker compose run --rm web bash which yarn
> /usr/local/bin/yarn
> 
> > docker compose run --rm web bash yarn -v
> node:internal/modules/cjs/loader:988
>   throw err;
>   ^
> 
> Error: Cannot find module '/usr/src/app/web/yarn.js'
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
>     at Function.Module._load (node:internal/modules/cjs/loader:833:27)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
>     at node:internal/main/run_main_module:22:47 {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: []
> }
> ```
> 
> ![スクリーンショット 2022-10-16 19 27 52](https://user-images.githubusercontent.com/33239435/196030382-8118b74a-b439-4916-ae41-3762b3dad10e.png)

```shell
> docker compose run --rm web bash -c "yarn"
yarn install v1.22.19
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.54s.

> docker compose run --rm web bash -c "yarn -v"
1.22.19
```

**Comment by Hamumayo55** [comment]
```
web_1  | ready - started server on 0.0.0.0:3000, url: http://localhost:3000
web_1  | Error: Could not find a production build in the '/usr/src/app/web/.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id
web_1  |     at NextNodeServer.getBuildId (/usr/src/app/web/node_modules/next/dist/server/next-server.js:169:23)
web_1  |     at new Server (/usr/src/app/web/node_modules/next/dist/server/base-server.js:58:29)
web_1  |     at new NextNodeServer (/usr/src/app/web/node_modules/next/dist/server/next-server.js:70:9)
web_1  |     at NextServer.createServer (/usr/src/app/web/node_modules/next/dist/server/next.js:140:16)
web_1  |     at async /usr/src/app/web/node_modules/next/dist/server/next.js:149:31
```

**Comment by kagari** [comment]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/usr/local/lib/python3.10/site-packages/uvicorn/config.py", line 479, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/src/app/web/./main.py", line 2, in <module>
    from fastapi import (
ImportError: cannot import name 'BaseModel' from 'fastapi' (/usr/local/lib/python3.10/site-packages/fastapi/__init__.py)
```

**Comment by kagari** [comment]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/usr/local/lib/python3.10/site-packages/uvicorn/config.py", line 479, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/src/app/web/./main.py", line 11, in <module>
    error_name_pattern = re.compile("+[e|E]rror*")
  File "/usr/local/lib/python3.10/re.py", line 251, in compile
    return _compile(pattern, flags)
  File "/usr/local/lib/python3.10/re.py", line 303, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/local/lib/python3.10/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/local/lib/python3.10/sre_parse.py", line 950, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/local/lib/python3.10/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/local/lib/python3.10/sre_parse.py", line 668, in _parse
    raise source.error("nothing to repeat",
re.error: nothing to repeat at position 0
```

**Comment by soto0201** [comment]
```
npm ERR! code EAI_AGAIN
web_1     | npm ERR! syscall getaddrinfo
web_1     | npm ERR! errno EAI_AGAIN
web_1     | npm ERR! request to https://registry.yarnpkg.com/yocto-queue/-/yocto-queue-0.1.0.tgz failed, reason: getaddrinfo EAI_AGAIN registry.yarnpkg.com
web_1     |
web_1     | npm ERR! A complete log of this run can be found in:
web_1     | npm ERR!     /root/.npm/_logs/2022-10-17T06_44_04_738Z-debug-0.log
web_1     | e_2202_web_1 exited with code 1
```

**Comment by Hamumayo55** [comment]
```
Traceback (most recent call last):
  File "/usr/local/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/usr/local/lib/python3.10/site-packages/mypy/__main__.py", line 15, in console_entry
    main()
  File "mypy/main.py", line 95, in main
  File "mypy/main.py", line 174, in run_build
  File "mypy/build.py", line 187, in build
  File "mypy/build.py", line 270, in _build
  File "mypy/build.py", line 2867, in dispatch
  File "mypy/build.py", line 3244, in process_graph
  File "mypy/build.py", line 3322, in process_fresh_modules
  File "mypy/build.py", line 2087, in load_tree
  File "mypy/nodes.py", line 398, in deserialize
  File "mypy/nodes.py", line 3658, in deserialize
  File "mypy/nodes.py", line 3599, in deserialize
  File "mypy/nodes.py", line 275, in deserialize
  File "mypy/nodes.py", line 3073, in deserialize
  File "mypy/nodes.py", line 3658, in deserialize
  File "mypy/nodes.py", line 3599, in deserialize
  File "mypy/nodes.py", line 275, in deserialize
  File "mypy/nodes.py", line 843, in deserialize
  File "mypy/types.py", line 189, in deserialize_type

  File "mypy/types.py", line 1996, in deserialize
KeyError: 'unpack_kwargs'
```

**Comment by Hamumayo55** [comment]
```console
Traceback (most recent call last):
  File "/usr/src/app/web/test_main.py", line 3, in <module>
    from .main import app
ImportError: attempted relative import with no known parent package
```

**Comment by kagari** [comment]
pre-commit設定時にエラーが出た

```
$ vim .git/hooks/pre-commit

$ git commit -m "URLの正規表現を作成した"                                                                                                                                         [feature/#22_remove_file_path_and_URL]
hint: The '.git/hooks/pre-commit' hook was ignored because it's not set as executable.
hint: You can disable this warning with `git config advice.ignoredHook false`.
[feature/#22_remove_file_path_and_URL 25c0acb] URLの正規表現を作成した
 1 file changed, 2 insertions(+)
```

実行権限をつけたら良い `chmod 755 .git/hooks/pre-commit`

**Comment by Hamumayo55** [comment]
Python
```
File "/usr/src/app/web/main.py", line 41, in __main__.parse_error
Failed example:
    asyncio.run(parse_error(ErrorContents(**error_text_query)))
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/doctest.py", line 1346, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest __main__.parse_error[1]>", line 1, in <module>
        asyncio.run(parse_error(ErrorContents(**error_text_query)))
    NameError: name 'error_text_query' is not defined
```
