### ISSUE TITLE
自作スクリプト内でエラーが出た際に，そのファイル名や行の情報も重要な情報として抽出する（Python）

### ISSUE THREAD

**Issue by kagari** [jphacks/E_2202#78]
# 背景
現在は自作スクリプトは重要な情報として取得していない．
ただ，私達がコードのエラー箇所を特定するためにファイル名と行番号，行テキストを見ることが多い．
そのため，自作スクリプトのファイル名や行番号，行テキストを重要な情報として抽出・表示する．

例（28，29行目を強調表示する）
<img width="500" alt="image" src="https://user-images.githubusercontent.com/33239426/199769217-c72c9170-49c6-4b44-97e6-28623d7299ee.png">

# 目的
自作スクリプトのファイル名や行番号，行テキストを重要な情報として抽出・表示する．

# やること
- [ ] そのため，自作スクリプトのファイル名や行番号，行テキストを重要な情報として抽出・表示する．

**Comment by kagari** [comment]
- [ ] https://github.com/jphacks/E_2202/discussions/36#discussioncomment-3915574
- [ ] https://github.com/jphacks/E_2202/discussions/36#discussioncomment-3914113
- [ ] https://github.com/jphacks/E_2202/discussions/36#discussioncomment-3906291
- [ ] https://github.com/jphacks/E_2202/discussions/36#discussioncomment-3914052
- [ ] https://github.com/jphacks/E_2202/discussions/36#discussioncomment-3914088

**Comment by kagari** [comment]
これがまだちょっとおかしい
```
File "/usr/src/app/web/main.py", line 41, in __main__.parse_error
Failed example:
    asyncio.run(parse_error(ErrorContents(**error_text_query)))
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/doctest.py", line 1346, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest __main__.parse_error[1]>", line 1, in <module>
        asyncio.run(parse_error(ErrorContents(**error_text_query)))
    NameError: name 'error_text_query' is not defined
```
